spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:schema.sql
    data: classpath:data.sql
    url:  jdbc:h2:mem:test_mem
    username: root
    password: 123456

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: deleted
      logic-not-delete-value: using

