spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    schema: classpath:schema.sql
#    data: classpath:data.sql
    url: jdbc:mysql://127.0.0.1/test
    username: root
    password: 123456
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: true

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: deleted
      logic-not-delete-value: using

